### PR TITLE
Replacing B family connectors

### PR DESCRIPTION
**Pull request by MRQ**
This is a complete replacement of the B family ( B, B/2, B/3; male and female). It fixes several issues for these:
  * #5 Rows are in wrong order on right angle connectors 
  * #4 Pin 24 should be named pin 24a 
  * #3 None of the footprints conform to KLC (With the exception, that there is no Pin 1)

Here are some screenshots: [B064F](https://shells.aachen.ccc.de/~mrq/B064F_rev2.png), [B064M](https://shells.aachen.ccc.de/~mrq/B064M_rev2.png), [3B010M](https://shells.aachen.ccc.de/~mrq/3B010M_rev2.png)

I'm open for suggesting improvements.

### CODE REVIEW

**Comment by MRQ** [comment]
About the CI errors "Pad 1 not found in footprint" from `check_kicad_mod.py`:
For each fully populated connector in the B family, there is a version with only even pins populated. So these versions don't have a Pin 1A. For consistency, I kept the coordinates the same, so they are not shifted to center 2A.

**Comment by poeschlr** [comment]
@MRQ sorry this got ignored for so long.
(We are currently a bit preoccupied by or work regarding preparations for the v5 release.)

The footprints look a lot better then the old ones. But i also see a problem with the alignment. (It seems a bit random to me where you placed the footprints.)
If you have time within the next few days, could you ensure that the lowest numbered pin is always located at the origin and that this pin is also on the top right? (all other pins are to the left, or bottom)

If i don't here back from you i will use your footprints as the basis for transferring over to the new repo. (I will then do the alignment my self.)

**Comment by MRQ** [comment]
My reasons for the choosen rotation were to keep the columns and rows (as they are called in the datasheets) aligned to Y- and X-axis respectively. I choose not to shift half populated versions, because than board designers can choose between the two without shifting the footprint in the layout.

Lowest pin number to top left means:
  1. rotating the female connectors by 90° counter-clockwise
  2. shifting half populated versions by one pin, so that 2A is at the origin.

So should I do these steps? Then I will do this in the next week.

**Comment by poeschlr** [comment]
For some reason i missed your answer in all the messages that i get.

After thinking about it for some time it is ok to have them centered around the imaginary pad A1 (for connectors that miss them.)
I would still suggest to rotate the female version by 90 degree counter clockwise.

**Comment by MRQ** [comment]
Please hold on. The footprint is rotated now, but the text is not. I will fix this soon.

**Comment by MRQ** [comment]
I'm done so far. In case you are interested, the generating code is here: https://github.com/MRQ/kicad-footprint-generator/blob/master/scripts/Connectors_IEC_DIN/generate_din41612.py

**Comment by poeschlr** [comment]
Looks good. Thanks for your contribution.

Could you also open a pull request over at the script repo? https://github.com/pointhi/kicad-footprint-generator

If you do so, link to this pull request to tell @pointhi that your footprints have been merged.

**Pull request merged**
